# Generated by Django 4.0.6 on 2023-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0004_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
