# Generated by Django 4.0.6 on 2023-03-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0005_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ids',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
