# Generated by Django 4.0.6 on 2023-03-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0006_order_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
    ]
