# Generated by Django 4.0.6 on 2022-08-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='images/%y/%m/%d')),
                ('image2', models.ImageField(upload_to='images/%y/%m/%d')),
                ('category', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('flavor', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
            ],
        ),
    ]
