# Generated by Django 4.0.6 on 2023-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_product_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=75)),
                ('message', models.CharField(max_length=1010)),
            ],
        ),
    ]
